import { readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const dataDir = path.join(rootDir, "data");
const outputPath = path.join(rootDir, "src", "data", "generatedLibrary.ts");

function toPosix(filePath) {
  return filePath.split(path.sep).join("/");
}

function importPathFromGenerated(relativePath) {
  return `../../data/${toPosix(relativePath)}?raw`;
}

async function directoryExists(directory) {
  try {
    const stats = await readdir(directory);
    return Array.isArray(stats);
  } catch {
    return false;
  }
}

async function listEntries(directory) {
  try {
    return await readdir(directory, { withFileTypes: true });
  } catch {
    return [];
  }
}

async function collectFiles(directory, baseRelativePath = "") {
  const entries = await listEntries(directory);
  const files = [];

  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    if (entry.name === ".git") {
      continue;
    }

    const relativePath = baseRelativePath ? `${baseRelativePath}/${entry.name}` : entry.name;
    const fullPath = path.join(directory, entry.name);

    if (entry.isDirectory()) {
      files.push(...(await collectFiles(fullPath, relativePath)));
      continue;
    }

    if (entry.isFile()) {
      files.push(relativePath);
    }
  }

  return files;
}

async function collectPromptAssets() {
  const promptsDir = path.join(dataDir, "prompts");
  if (!(await directoryExists(promptsDir))) {
    return [];
  }

  const files = await collectFiles(promptsDir, "prompts");
  return files
    .filter((file) => file.toLowerCase().endsWith(".md"))
    .map((relativePath) => ({
      type: "prompt",
      relativePath,
      sourceName: path.basename(relativePath),
    }));
}

async function collectFolderAssets(folderName, entryFile, type) {
  const folderDir = path.join(dataDir, folderName);
  const entries = await listEntries(folderDir);
  const assets = [];

  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    if (!entry.isDirectory()) {
      continue;
    }

    const assetRoot = path.join(folderDir, entry.name);
    const allFiles = await collectFiles(assetRoot, `${folderName}/${entry.name}`);
    const entryPath = `${folderName}/${entry.name}/${entryFile}`;

    if (!allFiles.includes(entryPath)) {
      continue;
    }

    assets.push({
      type,
      relativePath: entryPath,
      sourceName: entry.name,
      resourcePaths: allFiles.filter((file) => file !== entryPath).sort((a, b) => a.localeCompare(b)),
    });
  }

  return assets;
}

const assets = [
  ...(await collectPromptAssets()),
  ...(await collectFolderAssets("skills", "SKILL.md", "skill")),
  ...(await collectFolderAssets("tools", "README.md", "tool")),
].sort((a, b) => a.relativePath.localeCompare(b.relativePath));

const imports = assets
  .map((asset, index) => `import asset${index} from ${JSON.stringify(importPathFromGenerated(asset.relativePath))};`)
  .join("\n");

const entries = assets
  .map((asset, index) => {
    const resourcePaths = asset.resourcePaths?.length
      ? `,\n    resourcePaths: ${JSON.stringify(asset.resourcePaths, null, 2).replace(/\n/g, "\n    ")}`
      : "";
    return `  {
    type: ${JSON.stringify(asset.type)},
    markdown: asset${index},
    relativePath: ${JSON.stringify(asset.relativePath)},
    sourceName: ${JSON.stringify(asset.sourceName)}${resourcePaths},
  }`;
  })
  .join(",\n");

const contents = `// This file is generated by scripts/generate-library.mjs. Do not edit by hand.
${imports}

export const generatedLibraryName = "data";

export const generatedLibrarySources = [
${entries}
] as const;
`;

await writeFile(outputPath, contents, "utf8");
console.log(`Generated ${toPosix(path.relative(rootDir, outputPath))} with ${assets.length} assets.`);
