// This file is generated by scripts/generate-library.mjs. Do not edit by hand.
import asset0 from "../../data/prompts/code-review.md?raw";
import asset1 from "../../data/prompts/commit-message.md?raw";
import asset2 from "../../data/prompts/rubber-duck.md?raw";
import asset3 from "../../data/skills/api-design/SKILL.md?raw";
import asset4 from "../../data/skills/pdf-handling/SKILL.md?raw";
import asset5 from "../../data/tools/mcp-inspector/README.md?raw";
import asset6 from "../../data/tools/openspec/README.md?raw";

export const generatedLibraryName = "data";

export const generatedLibrarySources = [
  {
    type: "prompt",
    markdown: asset0,
    relativePath: "prompts/code-review.md",
    sourceName: "code-review.md",
  },
  {
    type: "prompt",
    markdown: asset1,
    relativePath: "prompts/commit-message.md",
    sourceName: "commit-message.md",
  },
  {
    type: "prompt",
    markdown: asset2,
    relativePath: "prompts/rubber-duck.md",
    sourceName: "rubber-duck.md",
  },
  {
    type: "skill",
    markdown: asset3,
    relativePath: "skills/api-design/SKILL.md",
    sourceName: "api-design",
  },
  {
    type: "skill",
    markdown: asset4,
    relativePath: "skills/pdf-handling/SKILL.md",
    sourceName: "pdf-handling",
    resourcePaths: [
      "skills/pdf-handling/assets/sample-pipeline.json",
      "skills/pdf-handling/references/extraction-checklist.md"
    ],
  },
  {
    type: "tool",
    markdown: asset5,
    relativePath: "tools/mcp-inspector/README.md",
    sourceName: "mcp-inspector",
  },
  {
    type: "tool",
    markdown: asset6,
    relativePath: "tools/openspec/README.md",
    sourceName: "openspec",
    resourcePaths: [
      "tools/openspec/templates/change-proposal.md"
    ],
  }
] as const;
