// This file is generated by scripts/generate-library.mjs. Do not edit by hand.
import asset0 from "../../assets/api-design/README.md?raw";
import asset1 from "../../assets/code-review/README.md?raw";
import asset2 from "../../assets/commit-message/README.md?raw";
import asset3 from "../../assets/mcp-inspector/README.md?raw";
import asset4 from "../../assets/openspec/README.md?raw";
import asset5 from "../../assets/pdf-handling/README.md?raw";
import asset6 from "../../assets/rubber-duck/README.md?raw";

export const generatedLibraryName = "assets";

export const generatedLibrarySources = [
  {
    markdown: asset0,
    relativePath: "assets/api-design/README.md",
    sourceName: "api-design",
    resourcePaths: [
      "assets/api-design/SKILL.md"
    ],
  },
  {
    markdown: asset1,
    relativePath: "assets/code-review/README.md",
    sourceName: "code-review",
  },
  {
    markdown: asset2,
    relativePath: "assets/commit-message/README.md",
    sourceName: "commit-message",
  },
  {
    markdown: asset3,
    relativePath: "assets/mcp-inspector/README.md",
    sourceName: "mcp-inspector",
  },
  {
    markdown: asset4,
    relativePath: "assets/openspec/README.md",
    sourceName: "openspec",
    resourcePaths: [
      "assets/openspec/templates/change-proposal.md"
    ],
  },
  {
    markdown: asset5,
    relativePath: "assets/pdf-handling/README.md",
    sourceName: "pdf-handling",
    resourcePaths: [
      "assets/pdf-handling/assets/sample-pipeline.json",
      "assets/pdf-handling/references/extraction-checklist.md",
      "assets/pdf-handling/SKILL.md"
    ],
  },
  {
    markdown: asset6,
    relativePath: "assets/rubber-duck/README.md",
    sourceName: "rubber-duck",
  }
] as const;
